name: meal_room_shell
description: Flutter shell for MealRoom React web app
publish_to: none
version: 0.1.0+1
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  connectivity_plus: ^6.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
flutter:
  uses-material-design: true
  assets:
    - assets/icon-meal-room.png
    - assets/icon-meal-room-transparent.png
    - assets/web/
    - assets/web/assets/

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon-meal-room-transparent.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-meal-room-transparent.png"
